name: Build and Package Lambda Layer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create_release:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      # Step 1: Create a release with Release Please
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - name: Debug Release Please outputs
        if: ${{ steps.release.outputs.pr }}
        run: |
          echo "PR Branch: ${{ steps.release.outputs.pr }}"
          echo "PR Branch: ${{ steps.release.outputs.prs }}"
          echo "Release Branch: ${{ steps.release.outputs.releaseBranch }}"
          echo "All outputs: ${{ toJSON(steps.release.outputs) }}"
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created == false }}
        with:
          ref: 'release-please--branches--main'

      - name: Package with SAM
        if: ${{ steps.release.outputs.release_created == false }}
        run: npm run build

      - name: Create zip from SAM artifacts
        if: ${{ steps.release.outputs.release_created == false }}
        run: |
          rm -rf build
          mkdir build
          cd .aws-sam/build
          zip -r ../../build/lambda-layer.zip .
          ls -la
          pwd
          ls
          cd ../..
          ls
          pwd

      # Commit and push the changes
      - name: Commit changes
        if: ${{ steps.release.outputs.release_created == false }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add build/lambda-layer.zip
          git commit -m "chore: update version.txt for $VERSION"
          git push