name: Build and Package Lambda Layer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/sam/build-nodejs20.x:1
      
    steps:
    - uses: actions/checkout@v4
        
    - name: Setup AWS SAM CLI
      uses: aws-actions/setup-sam@v2
        
    - name: Package with SAM
      run: npm run package
      
    - name: Create zip from SAM artifacts
      run: |
        cd .aws-sam/build
        zip -r ../../lambda-layer.zip .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sharp-heic-lambda-layer
        path: lambda-layer.zip